- pom.xml
- src/main/java/org/verapdf/pdfa/qa/AbstractTestCorpus.java
- src/main/java/org/verapdf/pdfa/qa/CorpusDetails.java
- src/main/java/org/verapdf/pdfa/qa/CorpusDetailsImpl.java
- src/main/java/org/verapdf/pdfa/qa/CorpusItem.java
- src/main/java/org/verapdf/pdfa/qa/CorpusItemId.java
- src/main/java/org/verapdf/pdfa/qa/CorpusItemIdImpl.java
- src/main/java/org/verapdf/pdfa/qa/CorpusItemImpl.java
- src/main/java/org/verapdf/pdfa/qa/ResultSet.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetDetails.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetDetailsImpl.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetImpl.java
- src/main/java/org/verapdf/pdfa/qa/TestCorpus.java
- src/main/java/org/verapdf/pdfa/qa/ZipBackedTestCorpus.java
- src/test/java/org/verapdf/integration/CorpusManager.java
- src/test/java/org/verapdf/integration/ITVeraCorpusTests.java
- src/test/java/org/verapdf/pdfa/validators/ValidatorTest.java
- src/test/resources/org/verapdf/integration/templates/corpus-results.mustache
MVP test result publishing for veraPDF Integration tests. Still needs:
- better info in the display
- styling
- comparison with previous results
> Feature test reporting

- pom.xml
- src/main/java/org/verapdf/pdfa/qa/ResultSetDetails.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetDetailsImpl.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetImpl.java
- src/test/resources/org/verapdf/integration/templates/corpus-results.mustache
- Using parent pom.
- Reporting dependency details.
> Feat release details

- pom.xml
- src/main/java/org/verapdf/pdfa/qa/ResultSetImpl.java
- src/test/java/org/verapdf/pdfa/validators/ValidatorTest.java
Needs PRs: veraPDF/veraPDF-library#548 and veraPDF/veraPDF-pdfbox-validation#33
> Auto validation

- README.md
- src/test/resources/org/verapdf/integration/templates/corpus-results.mustache
- stylesheet not internal again; and
- added README with local test instructions.
> FIX - internal stylesheet

- pom.xml
- bumped -> 0.15 for development;
- dependencies no longer managed in parent;
- added failsafe version; and
- updated dependecies for testing.
> Dev - 0.15 development:

- .travis.yml
- src/main/java/org/verapdf/pdfa/qa/ResultSet.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetImpl.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetSummary.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetSummaryImpl.java
- src/test/java/org/verapdf/integration/ITVeraCorpusTests.java
- src/test/resources/org/verapdf/integration/templates/test-summary.mustache
- split corpus test output to sub-dirs;
- disabled default output to stdout;
- HTML reporting for test summary in root dir;
- exception detection in corpus tests;
- stack trace reporting for test exceptions; and
- fixes #21.
> FEAT - Test summaries and enhanced reporting.

- src/test/java/org/verapdf/integration/CorpusManager.java
- src/test/java/org/verapdf/integration/ITVeraCorpusTests.java
- added 1a, 2u, and 3b flavour tests.
> FEAT - New corpus tests

- pom.xml
- bumped minor -> 0.18 for release;
- updated library and pdfbox-validation dependencies; and
- updated parent dependency in pom.xml.
> REL - Release 0.18

- pom.xml
- bumped minor -> 0.19 for development; and
- updated pdfbox-validation and library dependencies.
> REL - Development release 0.19

- pom.xml
- bumped minor -> 0.20 for release; and
> REL - Release 0.20

- pom.xml
- bumped minor -> 0.21 for development; and
> DEV - Development version 0.21

- pom.xml
- bumped minor -> 0.22 for release; and
> REL - Release 0.22

- pom.xml
- bumped minor -> 0.23 for development; and
> DEV - Development version 0.23

- src/test/java/org/verapdf/pdfa/validators/ValidatorTest.java
- cleaned up exception handling.
> FEAT - refactor processing API

- pom.xml
- bumped minor -> 0.24 for release; and
> REL - Release 0.24

- pom.xml
- bumped minor -> 0.25 for development; and
> DEV - Development version 0.25

- src/test/java/org/verapdf/integration/CorpusManager.java
- changed broken Isartor URL to new veraPDF hosted loctation.
> FIX - Isartor download URL

- src/main/java/org/verapdf/pdfa/qa/ResultSetImpl.java
- src/test/java/org/verapdf/pdfa/validation/validators/ValidatorTest.java
- renamed parser interface; and
- changed serialisation args to primitives.
> REFACT - Stream processor

- pom.xml
- bumped minor -> 0.26 for release; and
- updated library, pdfbox-valdiation and greenfield-validation dependencies.
> REL - Release 0.26

- pom.xml
- bumped minor -> 0.27 for development; and
> DEV - Development version 0.27

- pom.xml
- bumped minor -> 0.29 for development; and
> DEV - Development version 0.29

- license/template/license.txt
- pom.xml
- src/main/java/org/verapdf/pdfa/qa/AbstractTestCorpus.java
- src/main/java/org/verapdf/pdfa/qa/CorpusDetails.java
- src/main/java/org/verapdf/pdfa/qa/CorpusDetailsImpl.java
- src/main/java/org/verapdf/pdfa/qa/CorpusItem.java
- src/main/java/org/verapdf/pdfa/qa/CorpusItemId.java
- src/main/java/org/verapdf/pdfa/qa/CorpusItemIdImpl.java
- src/main/java/org/verapdf/pdfa/qa/CorpusItemImpl.java
- src/main/java/org/verapdf/pdfa/qa/CorpusManager.java
- src/main/java/org/verapdf/pdfa/qa/CorpusSampler.java
- src/main/java/org/verapdf/pdfa/qa/GitHubBackedProfileDirectory.java
- src/main/java/org/verapdf/pdfa/qa/ProfilesMerger.java
- src/main/java/org/verapdf/pdfa/qa/ResultSet.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetDetails.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetDetailsImpl.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetImpl.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetSummary.java
- src/main/java/org/verapdf/pdfa/qa/ResultSetSummaryImpl.java
- src/main/java/org/verapdf/pdfa/qa/RuleDirectory.java
- src/main/java/org/verapdf/pdfa/qa/TestCorpus.java
- src/main/java/org/verapdf/pdfa/qa/ZipBackedTestCorpus.java
- src/test/java/org/verapdf/integration/CorpusTest.java
- src/test/java/org/verapdf/pdfa/validation/validators/ValidatorTest.java
- src/test/java/org/verapdf/pdfa/validators/ProfilesTest.java
- bumped minor -> 1.1 for development; and
> DEV - Development version 1.1

- pom.xml
- bumped minor -> 1.3 for development; and
> DEV - Development version 1.3

- .travis.yml
- removed erroneously added coverity section from `.travis.yml`.
> FIX - Remove coverity

- .travis.yml
- changed Codacy coverage reporting installer in line with new instructions.
> FIX - Codacy reporting

- README.md
- pom.xml
- bumped minor to 1.4 for release;
- updated README build instructions; and
- updated README badges.
> REL - Release v1.4

- pom.xml
- bumped minor -> 1.5 for development; and
- updated `org.verapdf` Maven dependencies.
> DEV - Development 1.5

- pom.xml
- bumped minor -> 1.6 for release;
- updated validation and pdfbox-validation dependencies.
> REL - Release v1.6

- pom.xml
- bumped minor -> 1.7 for development; and
> REL - Development version v1.7

- src/main/java/org/verapdf/pdfa/qa/GitHubBackedProfileDirectory.java
- caught and logged GitHub Profile 404, but continue tests.
> FIX - Profile 404

- pom.xml
- bumped minor -> 1.8 for release;
- updated validation and pdfbox-validation dependencies.
> REL - Release v1.8

- pom.xml
- bumped minor -> 1.10 for release; and
- updated validation and pdfbox-validation dependencies.
> REL - Release v1.10

- .travis.yml
- pom.xml
- src/main/java/org/verapdf/pdfa/qa/GitHubBackedProfileDirectory.java
- src/main/java/org/verapdf/pdfa/qa/ProfilesMerger.java
Merging version 1.12 to master.
> Rel - Release v1.12

- pom.xml
- src/test/java/org/verapdf/pdfa/validators/test/ProfilesTest.java
- bumped minor version to 1.18
- using parent POM v1.18.1
> REL - veraPDF v1.18

- README.md
- pom.xml
- src/test/java/org/verapdf/pdfa/validation/validators/test/ValidatorTest.java
- src/test/java/org/verapdf/pdfa/validators/test/ProfilesTest.java
bumped minor version; and
using parent POM v1.20.1
updated profiles branch
> RС - Pre-release v1.20

- README.md
- pom.xml
- src/test/java/org/verapdf/pdfa/validation/validators/test/ValidatorTest.java
- src/test/java/org/verapdf/pdfa/validators/test/ProfilesTest.java
- bumped minor version to 1.20
> REL - Release v1.20

- pom.xml
- veraPDF-integration/pom.xml
- veraPDF-integration/src/test/java/org/verapdf/pdfa/validation/validators/test/ValidatorTest.java
- veraPDF-integration/src/test/java/org/verapdf/pdfa/validators/test/ProfilesTest.java
- veraPDF-pdf-regression-tests/pom.xml
- veraPDF-wcag-regression-tests/pom.xml
- veraPDF-wcag-regression-tests/src/main/java/org/verapdf/wcag/regression/tests/RegressionTestUtils.java
- bumped minor version to 1.22
- changed test files branch to rel/1.22
> REL - Release v1.22

- pom.xml
- veraPDF-integration/pom.xml
- veraPDF-pdf-regression-tests/pom.xml
- veraPDF-wcag-regression-tests/pom.xml
- bumped version -> 1.23
- updated dependency ranges
> DEV: v1.23

- README.md
- pom.xml
- veraPDF-integration/pom.xml
- veraPDF-integration/src/main/java/org/verapdf/pdfa/qa/RegressionTestingHelper.java
- veraPDF-integration/src/test/java/org/verapdf/pdfa/validation/validators/test/ValidatorTest.java
- veraPDF-integration/src/test/java/org/verapdf/pdfa/validators/test/ProfilesTest.java
- veraPDF-pdf-regression-tests/pom.xml
- veraPDF-wcag-regression-tests/pom.xml
- bumped minor version to 1.24
- changed test files branch to rel/1.24
> REL - Release v1.24

- .github/workflows/test-pr.yml
- README.md
- pom.xml
- veraPDF-integration/pom.xml
- veraPDF-integration/src/main/java/org/verapdf/pdfa/qa/RegressionTestingHelper.java
- veraPDF-integration/src/test/java/org/verapdf/pdfa/validation/validators/test/ValidatorTest.java
- veraPDF-integration/src/test/java/org/verapdf/pdfa/validators/test/ProfilesTest.java
- veraPDF-pdf-regression-tests/pom.xml
- veraPDF-wcag-regression-tests/pom.xml
- veraPDF-wcag-regression-tests/src/main/java/org/verapdf/wcag/regression/tests/WCAGRegressionTestUtils.java
- bumped minor version to 1.24
- changed test files branch to rel/1.24
> REL - Release v1.24 (jakarta)

- README.md
- pom.xml
- veraPDF-integration/pom.xml
- veraPDF-pdf-regression-tests/pom.xml
- veraPDF-wcag-regression-tests/pom.xml
- bumped version -> 1.27
- updated maven dependency
- updated readme
> DEV: v1.27

- README.md
- pom.xml
- veraPDF-integration/pom.xml
- veraPDF-integration/src/main/java/org/verapdf/pdfa/qa/AbstractTestCorpus.java
- veraPDF-integration/src/main/java/org/verapdf/pdfa/qa/RegressionTestingHelper.java
- veraPDF-integration/src/test/java/org/verapdf/pdfa/validation/validators/test/ValidatorTest.java
- veraPDF-integration/src/test/java/org/verapdf/pdfa/validators/test/ProfilesTest.java
- veraPDF-pdf-regression-tests/pom.xml
- veraPDF-wcag-regression-tests/pom.xml
- veraPDF-wcag-regression-tests/src/main/java/org/verapdf/wcag/regression/tests/WCAGRegressionTestUtils.java
- bumped minor version to 1.28
- changed test files branch to rel/1.28
> REL - Release v1.28

- README.md
- pom.xml
- veraPDF-integration/pom.xml
- veraPDF-integration/src/main/java/org/verapdf/pdfa/qa/AbstractTestCorpus.java
- veraPDF-integration/src/main/java/org/verapdf/pdfa/qa/RegressionTestingHelper.java
- veraPDF-integration/src/test/java/org/verapdf/pdfa/validation/validators/test/ValidatorTest.java
- veraPDF-integration/src/test/java/org/verapdf/pdfa/validators/test/ProfilesTest.java
- veraPDF-pdf-regression-tests/pom.xml
- veraPDF-wcag-regression-tests/pom.xml
- veraPDF-wcag-regression-tests/src/main/java/org/verapdf/wcag/regression/tests/WCAGRegressionTestUtils.java
- bumped minor version to 1.28
- changed test files branch to rel/1.28
> REL - Release v1.28 (jakarta)
